name: exos-agent

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  exos-agent:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /exos-agent') ||
      startsWith(github.event.comment.body, '/exos-agent')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Run exos-agent
        uses: BlackXV2vip/agent-exos/github@2c14fc5586fe0b88e5c04732d2e846769cc35671 # latest
        env:
          EXOS_AGENT_API_KEY: ${{ secrets.EXOS_AGENT_API_KEY }}
          EXOS_AGENT_PERMISSION: '{"bash": "deny"}'
        with:
          model: exos-agent/claude-opus-4-5
